This is makeindex, version 2.15 [TeX Live 2019] (kpathsea + Thai support).
Scanning style file ./report.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file report.acn....done (22 entries accepted, 0 rejected).
Sorting entries....done (106 comparisons).
Generating output file report.acr....done (27 lines written, 0 warnings).
Output written in report.acr.
Transcript written in report.alg.
